# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
#schedule:
# - cron: "0 0 * * *"

on:
  push:
    paths:
      - flexboard_example/index.Rmd

name: render-rmarkdown

jobs:
  render:
    name: Render my document
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@v1
        
      - name: Install packages
        run: |
          R -e 'install.packages("rjson")'
          R -e 'install.packages("xts")'
          R -e 'install.packages("dplyr")'
          R -e 'install.packages("dygraphs")'
          R -e 'install.packages("rmarkdown")'
          R -e 'install.packages("flexdashboard")'
          R -e 'install.packages("lubridate")'

      - name: Render my document to all types
        run: Rscript -e 'rmarkdown::render("flexboard_example/index.Rmd", output_format = "all")'
      - name: Commit results
        run: |
          git add flexboard_example/index.Rmd*
          git commit -m 'Re-build my-document' || echo "No changes to commit"
          git push origin master || echo "No changes to commit"
